#!/bin/bash

# Split individual language data into train, val, test sets.

 main() {
     # ABJAD
     python3 data/scrape/lib/create_orth_dataset.py -orth=abjad
     # CYRLLIC
     python3 data/scrape/lib/create_orth_dataset.py -orth=cyrillic
     # LATIN
     python3 data/scrape/lib/create_orth_dataset.py -orth=latin
 }

 main