#!/bin/bash

# Split individual language data into train, val, test sets.

main() {
    # SPLIT URD
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/abjad/urd/urd_gold.tsv --language=urd -clean=y
    # SPLIT FAS
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/abjad/fas/fas_gold.tsv --language=fas -clean=y
    # SPLIT ARA
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/abjad/ara/ara_gold.tsv --language=ara
    # SPLIT PUS
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/abjad/pus/pus_gold.tsv --language=pus
    # SPLIT BUL
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/cyrillic/bul/raw/bul.tsv --language=bul -dedupe=y -clean=y
    # SPLIT HBS
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/latin/hbs/raw/hbs.tsv --language=hbs -dedupe=y
    # SPLIT MKD
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/cyrillic/mkd/raw/mkd.tsv --language=mkd -dedupe=y -clean=y
    # SPLIT RUS
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/cyrillic/rus/raw/rus.tsv --language=rus -dedupe=y -clean=y
    # SPLIT UKR
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/cyrillic/ukr/raw/ukr.tsv --language=ukr -dedupe=y -clean=y
    # SPLIT ENG
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/latin/eng/raw/eng.tsv --language=eng -dedupe=y
    # SPLIT IND
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/latin/ind/raw/ind.tsv --language=ind -dedupe=y
    # SPLIT SPA
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/latin/spa/raw/spa.tsv --language=spa -dedupe=y
    # SPLIT TGL
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/latin/tgl/raw/tgl.tsv --language=tgl -dedupe=y
    # SPLIT MON
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/latin/mon/raw/mon.tsv --language=mon -dedupe=y
    # SPLIT RON
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/cyrillic/ron/raw/ron.tsv --language=ron -dedupe=y
    # SPLIT HUN
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/cyrillic/hun/raw/hun.tsv --language=hun -dedupe=y
    # SPLIT HEB
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/abjad/heb/raw/heb.tsv --language=heb -dedupe=y
    # SPLIT AII
    python3 data/scrape/lib/split.py \
    --infile=data/scrape/tsv/abjad/aii/raw/aii.tsv --language=aii -dedupe=y
}

main